### ISSUE TITLE
New shows created have root as owner, not sc-sickchill

### ISSUE THREAD

**Issue by Ventje23** [BenjV/SYNO-packages#13]
New shows created with sichchill after upgrade to Python 3 are not owned by sc-sickchill, but root.

**Comment by BenjV** [comment]
Hmm I have to look into that.

**Comment by Ventje23** [comment]
Ok thanks for the super fast response. Much appreciated.
Hopefully you'll have a fix for all that have installed it already

**Comment by Mickroz** [comment]
same problem. subscribing

**Comment by BenjV** [comment]
@Ventje23 
For the files/folders you already have gotten you must change the permission yourself on the command line.
The gui does not support changing the ownership to a "hidden" package user like sc-sickchill.

Log into the commandline with putty.
Change the ownership of a folder with this command:

> sudo chown sc-sickchill:sickchill <complete foldername>

and the change the files and folders inside recursively with this command:

> sudo -R sc-sickchill:sickchill <complete foldername>

The alternative is just to delete them and let the new package(when I fixed it) download them again.

**Comment by Mickroz** [comment]
shouldn't that be
`sudo chown sc-sickchill:sc-download`
and
`sudo chown -R sc-sickchill:sc-download`

**Comment by BenjV** [comment]
No, the hidden group is sickchill not sc-sickchill

And by the way, the files are just getting the owner and permissions of the folder they were created in.
So if you use a nzb or torrent downloader, they put the file in some folder and the folders/file created there are getting the permissions and ownership of the top folder.
So you only have to make sure that that on that top folder the group sc-download has permissions and then whoever is the owner does not matter.

If you move files in the postprocessing of SickChill, the permission and ownership will be kept.
If you copy files in the postprocessing of  SickChill you get new files and they will inherent the permissions of the topfolder you are copying to.
So in that case you have to make sure that on that topfolder the group sc-download has the correct permissions.

**Comment by Mickroz** [comment]
you sure?
All my files/folders from the Synocommunity have sc-sickchill:sc-download permissions, same for couchpotato and the permissions for me are:
volume1 root:root
  /downloads Mickroz:sc-download
    /complete sc-sabnzbd:sc-download
      /tv sc-sabnzbd:sc-download
      /movies sc-sabnzbd:sc-download
  /series root:root
    /tv show folder sc-sickchill:sc-download
      /tv season folder sc-sickchill:sc-download
        /tv episode file sc-sickchill:sc-download
  /films root:root
    /movie folder sc-couchpotato:sc-download

and i move my files from the download folders, not copy.
All permissions are set within DSM.

**Comment by BKSteve** [comment]
> And by the way, the files are just getting the owner and permissions of the folder they were created in.
> So if you use a nzb or torrent downloader, they put the file in some folder and the folders/file created there are getting the permissions and ownership of the top folder.
> So you only have to make sure that that on that top folder the group sc-download has permissions and then whoever is the owner does not matter.
> 
> If you move files in the postprocessing of SickChill, the permission and ownership will be kept.
> If you copy files in the postprocessing of SickChill you get new files and they will inherent the permissions of the topfolder you are copying to.
> So in that case you have to make sure that on that topfolder the group sc-download has the correct permissions.

@BenjV  this is very interesting. Now I've taken a look at the 'Download Station' (DLS) hidden @download folders the main folder is DownloadStation as owner and group with the folder of the files created for the torrent as root/root with the files within all correctly set with the owner (creator of download) and group = users. 
When SC processes them using 'move files' it puts the root root on all the processed files as you describe above taking from the details from the folder they were in.
This would then seem to be a DLS issue however all the older downloads have the same root/root in @download but I have never seen the files come out to the completed folder with the root/root before. They always came out with the proper owner in accordance the DLS completed folders owner and group.

To further try and find the source of the problem I manually downloaded a new torrent with DLS which then correctly set the owner and group for both folders and files as expected in the completed folder. A new download sent to DLS from SC gives the, not expected, subfolder in the completed folder as root/root but with files correctly set. 
Clearly a different result than the torrent loaded to DLS manually.
Therefore I can only assume that the information passed from SC to DLS has something more in it to cause DLS to then produce a folder with root/root in the completed folder.

**Comment by Ventje23** [comment]
@BenjV,

hi I have just added one show under the Pytnon 3 version (so just one filder with wrong rights), I could probably also delete that one and add it again add soon as you have fixed the package.

Any ideas when you have a fix ready? I only see this right now: "Delete SickChill Python3 V 1.0.spk" I guess that's not the file with the fix.

**Comment by BKSteve** [comment]
> 
> 
> @BenjV,
> 
> hi I have just added one show under the Pytnon 3 version (so just one filder with wrong rights), I could probably also delete that one and add it again add soon as you have fixed the package.
> 
> Any ideas when you have a fix ready? I only see this right now: "Delete SickChill Python3 V 1.0.spk" I guess that's not the file with the fix.

The method I use to fix the new folder created with permissions you don't like and want to change.
Go to folder above with permissions I like and want everything below to have.

- Properties > General >Tick the box for apply to this folder, subfolders and files. Click OK
- Properties > Permission >Tick the box for apply to this folder, subfolders and files. Click OK

Done.

**Comment by BenjV** [comment]
@BKSteve 

In SickChill you configure a folder where DownloadStation will put the the downloaded files when finished.
The files will get the permissions of that folder and if you choose "Move" in the PostProcessing" of SIcKChill then will keep those owner and permisions.

Normally that would be another folder then where you put the file which you manually started in DownloadStation and so could have other owner/permisions.

**Comment by BKSteve** [comment]
@BenjV 
I just experimented right now. Added a new series to Sickchill.
The new folder created by Sickchill for the New show is created root/root.

I then did 1 download file manually and 1 auto via Sickchill.
Both folders appear in the configured Finished folder with the superior folder's permissions. Working correctly.

Processing the two downloads without changing the 'New show' folder permissions sets the two files to root/root

Then setting the permissions on 'New show' to owner/users, deleted the root/root episodes, recopied out of DLS to the 'Finished' folder both eps with [owner/users]. Rescanned files in Sickchill so no files or details in database. 
Reprocessed the 2 files manually using move. 
Both files are moved with root/root not owner/users per the folder details of the Finished folder or the New Show folder.

So the previous info on DLS folders is not correct or fixed as I still have one folder in recyclebin with the root/root permissions from Finished folder.

SickChill Info: Branch: master
Commit: f8f5e604429802b21b6e6364f60e17619d84a253
Version: v2020.09.08-1

**Comment by BenjV** [comment]
I know it is not fixed.
The package I made was running as root, that is a bug of the package
I have to fix this, that is why I removed the package.

**Comment by Ventje23** [comment]
@BenjV 

hi I tried to manual post-process files in Sickchill and noticed that after a manual post processing the processed files don't have any permissions. It only has an owner (in my perticular case is is sc-nzbget).

I don't know if this is related to way it's installed or that it is a Sickchill 'bug'

Any ideas?

**Comment by BenjV** [comment]
No that is the way DSM works when ACL's are used.
Linux does not support ACL's so Synology created a layer on top  of it but of course on the commandline you cannot see anything of the ACL's, the commandline is pure Linux.

The SynoCommunity uses in their templates ACL's and my package is based on their template

**Comment by BenjV** [comment]
I rewrote the complete installation package for SickChill and posted it on this repositary.
Download the package to your PC for a manual install.

If you already have a SickChill version running, please make a backup from within SickChill.
Then remove that package, manual install the new one, start it and restore the backup from within SickChiil.

Enjoy.

**Comment by McEnnes** [comment]
Thanks for the good work!!

**Comment by McEnnes** [comment]
The package is working great, but i happened to see an error in the general settings, advanced settings tab.
Branch version: error: No branches found.

**Comment by BenjV** [comment]
Must be something in the config you restored.
I have two Nasses an cannot reproduce this.

Take a look in the config to see if things are ok there.
You cane find the config here.

> /var/packages/sickchill/target/var/config,ini


The setting you are looking for are:

>   branch = master
>   git_remote = origin
>   git_remote_url = https://github.com/SickChill/SickChill.git

They should either be absent or else the same as the above.
>

**Comment by McEnnes** [comment]
Thanks for the info.
I looked at this and this is what i see, looks right doesn't it?

git_reset = 1
  branch = master
  git_remote = origin
  git_remote_url = https://github.com/SickChill/SickChill.git
  cur_commit_hash = 23ad7189c5c3b310c041f087a7059f47e0cbdd9d
  cur_commit_branch = ""
  config_version = 8
  encryption_version = 0

I am running this on a Synology Ds718+
Is there anything else i can do? Should i remove  those three lines?

**Comment by McEnnes** [comment]
Just had an update and did a restart, error resolved.

**Comment by BenjV** [comment]
Must have been a SickChill issue and not a package iisue.

**Comment by Ventje23** [comment]
@BenjV ,

just wanted to let you know that I removed the show and corresponding folder that got the root permissions. Readded the show with Sickchill and it got the sc-download permissions.

Great work and lots of thanks for all your work. Much appreciated!

**Comment by BenjV** [comment]
I changed the folder name "SickBeard" to "src" because I created a template that I also use for other packages and "src" is a more telling name.
And to name it "sickchill" would create a very strange total path.

If you specify a data folder as argument then the config will be placed also on that location, so there was no need to specify that apart.

**Comment by PielieChicken** [comment]
Thanks, i used your latest package, first uninstalled the package i already had installed .
Now the ownership problem is solved.
