### ISSUE TITLE
SickChill doesn't start after update Git to v2.32.0

### ISSUE THREAD

**Issue by decharon** [BenjV/SYNO-packages#33]
After updating Git to version v2.32.0 SickChill wouldn't start anymore.

SickChill installed version: 99999999-1.3 | Newest online version: 20210329-1
Git version: 2.32.0-18
DSM version: 6.2.4-25556

**Comment by BenjV** [comment]
Cannot have anything to do with each other.
Medusa only uses git when installing or updating then it does a gitclone from github.
Just starting medusa does not use git at all.
Also updating from within medusa does not use git.

**Comment by decharon** [comment]
BenjV,

First of all, thank you for your reply.

You mention Medusa, but i'm talking about SickChill is there a simularity? 

It started with a Mako error, when i tried to update SickChill within the application itself. I thought the new update for Git would solve the problem.

**Comment by BenjV** [comment]
No difference here between Medusa and SickChill regarding the use of git.

If something got corrupted or you have a SickChill release that will not start, then you could download the package again and do a manual install.
The package will update SickChill to the latest available software on github by doing a git clone, but only if you install it, not when you just start the existing package.

Most likely you had the same problem I had a littler while ago, a corrupted SickChill release that would not start, but is fixed in the mean time.

**Comment by decharon** [comment]
Unfortunately reinstalling SickChill did not solve the problem. Do you have any other idea?

**Comment by BenjV** [comment]
Look in the logs.
Replace medusa, with sickchill in the location I mentioned.

**Comment by ejc1967** [comment]
Same problem here after just updating Git to 2.32.

This is my log from the begining of the update:
2021/07/16 18:31:31	(system) trigger sickchill 99999999-1.3 Begin start-stop-status stop
SickChill did not responde to the 'TERM' signal, so a forced kill will is needed.
/var/packages/sickchill/scripts/start-stop-status: line 74: kill: (24689) - No such process
2021/07/16 18:31:51	(system) trigger sickchill 99999999-1.3 End start-stop-status stop ret=[0]
2021/07/16 18:32:21	(system) trigger sickchill 99999999-1.3 Begin start-stop-status start
Writing PID: 6075 to /volume1/@appstore/sickchill/var/sickchill.pid

2021/07/16 18:32:23	(system) trigger sickchill 99999999-1.3 End start-stop-status start ret=[0]
2021/07/16 18:33:49	start sickchill 99999999-1.3 Begin start-stop-status stop
2021/07/16 18:33:49	start sickchill 99999999-1.3 End start-stop-status stop ret=[0]
2021/07/16 18:33:49	start sickchill 99999999-1.3 Begin start-stop-status start
Writing PID: 9791 to /volume1/@appstore/sickchill/var/sickchill.pid

Crashed. Removing pidfile!
removed '/volume1/@appstore/sickchill/var/sickchill.pid'
2021/07/16 18:33:51	start sickchill 99999999-1.3 End start-stop-status start ret=[3]
2021/07/16 18:33:52	(system) trigger sickchill 99999999-1.3 Begin start-stop-status stop
2021/07/16 18:33:52	(system) trigger sickchill 99999999-1.3 End start-stop-status stop ret=[0]
2021/07/16 18:34:03	start sickchill 99999999-1.3 Begin start-stop-status start
Writing PID: 10667 to /volume1/@appstore/sickchill/var/sickchill.pid

Crashed. Removing pidfile!
removed '/volume1/@appstore/sickchill/var/sickchill.pid'

Reinstall of your latest package doesn't help

SickChill version: 99999999-1.3
Git version: 2.32.0-18
DSM version: 6.2.4-25556

**Comment by BenjV** [comment]
Clearly a sickchill, problem, the package log looks normal for an application that crashes
Look in to see why it crashing.
 
var/packages/sickchill/target/var/Logs/application.log
